/* ================================================
   DATA: Versos del Corán seleccionados
   La traducción al español sigue la conocida edición
   bilingüe con tafsir publicada por el reino de
   Arabia Saudí (complejo del rey Fahd) en su versión
   en español, ampliamente difundida. El texto árabe
   sigue la escritura Uthmani estándar.
   ================================================ */
window.QURAN_DATA = {
  source: "Traducción de la 'Complejo del rey Fahd' (tafsir en español, Arabia Saudí) para la traducción; el texto árabe es Uthmani estándar.",
  categories: [
    "Paciencia", "Misericordia", "Perdón", "Oración", "Familia", "Conocimiento",
    "Dificultades", "Esperanza", "Arrepentimiento", "Paraíso", "Temor de Allah", "Fe"
  ],
  verses: [
    { category: "Paciencia", sura: "Al-Baqarah", suraNum: 2, ayah: 153, arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ", translation: "¡Creyentes! Buscad ayuda en la paciencia y en la oración. Allah está con los pacientes." },
    { category: "Paciencia", sura: "Al-'Ankabut", suraNum: 29, ayah: 69, arabic: "وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا ۚ وَإِنَّ اللَّهَ لَمَعَ الْمُحْسِنِينَ", translation: "A quienes luchen sinceramente por Nosotros les dirigiremos por Nuestro camino. Allah está, en verdad, con quienes hacen el bien." },
    { category: "Misericordia", sura: "Al-A'raf", suraNum: 7, ayah: 156, arabic: "وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ", translation: "Y Mi misericordia abarca todo." },
    { category: "Misericordia", sura: "Az-Zumar", suraNum: 39, ayah: 53, arabic: "قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَىٰ أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ ۚ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا", translation: "Di: '¡Siervos míos que habéis sido excesivos en contra de vosotros mismos, no desesperéis de la misericordia de Allah! Allah perdona todos los pecados. Él es el Perdonador, el Misericordiosísimo.'" },
    { category: "Misericordia", sura: "Al-Baqarah", suraNum: 2, ayah: 286, arabic: "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا", translation: "Allah no carga a nadie sino con lo que pueda sobrellevar." },
    { category: "Perdón", sura: "Az-Zumar", suraNum: 39, ayah: 53, arabic: "إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا ۚ إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ", translation: "Allah perdona todos los pecados. Él es el Perdonador, el Misericordiosísimo." },
    { category: "Perdón", sura: "Ash-Shura", suraNum: 42, ayah: 25, arabic: "وَهُوَ الَّذِي يَقْبَلُ التَّوْبَةَ عَنْ عِبَادِهِ وَيَعْفُو عَنِ السَّيِّئَاتِ", translation: "Él es quien acepta el arrepentimiento de Sus siervos y perdona las malas acciones." },
    { category: "Perdón", sura: "Al-Imran", suraNum: 3, ayah: 133, arabic: "وَسَارِعُوا إِلَىٰ مَغْفِرَةٍ مِّن رَّبِّكُمْ وَجَنَّةٍ عَرْضُهَا السَّمَاوَاتُ وَالْأَرْضُ أُعِدَّتْ لِلْمُتَّقِينَ", translation: "Apresuraos a obtener el perdón de vuestro Señor y un Jardín tan vasto como los cielos y la tierra, preparado para los piadosos." },
    { category: "Oración", sura: "Taha", suraNum: 20, ayah: 14, arabic: "إِنَّنِي أَنَا اللَّهُ لَا إِلَٰهَ إِلَّا أَنَا فَاعْبُدْنِي وَأَقِمِ الصَّلَاةَ لِذِكْرِي", translation: "Yo soy Allah, no hay más dios que Yo. ¡Adoradme y haced la oración para recordarme!" },
    { category: "Oración", sura: "Al-Baqarah", suraNum: 2, ayah: 45, arabic: "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ ۚ وَإِنَّهَا لَكَبِيرَةٌ إِلَّا عَلَى الْخَاشِعِينَ", translation: "Buscad ayuda en la paciencia y en la oración. Es algo difícil, salvo para los humildes." },
    { category: "Oración", sura: "Al-'Ankabut", suraNum: 29, ayah: 45, arabic: "إِنَّ الصَّلَاةَ تَنْهَىٰ عَنِ الْفَحْشَاءِ وَالْمُنكَرِ", translation: "La oración impide la indecencia y lo reprobable." },
    { category: "Familia", sura: "Al-Isra", suraNum: 17, ayah: 23, arabic: "وَقَضَىٰ رَبُّكَ أَلَّا تَعْبُدُوا إِلَّا إِيَّاهُ وَبِالْوَالِدَيْنِ إِحْسَانًا", translation: "Tu Señor ha decretado que no adoréis sino a Él y que os comportéis bien con vuestros padres." },
    { category: "Familia", sura: "Ar-Rum", suraNum: 30, ayah: 21, arabic: "وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً", translation: "Entre Sus signos está haberos creado esposas para que encontréis sosiego en ellas, y ha puesto entre vosotros amor y misericordia." },
    { category: "Familia", sura: "Luqman", suraNum: 31, ayah: 14, arabic: "وَوَصَّيْنَا الْإِنسَانَ بِوَالِدَيْهِ", translation: "Hemos ordenado al hombre respecto de sus padres." },
    { category: "Conocimiento", sura: "Taha", suraNum: 20, ayah: 114, arabic: "وَقُل رَّبِّ زِدْنِي عِلْمًا", translation: "Y di: '¡Señor mío, auméntame el conocimiento!'" },
    { category: "Conocimiento", sura: "Az-Zumar", suraNum: 39, ayah: 9, arabic: "قُلْ هَلْ يَسْتَوِي الَّذِينَ يَعْلَمُونَ وَالَّذِينَ لَا يَعْلَمُونَ", translation: "Di: '¿Son iguales quienes saben y quienes no saben?'" },
    { category: "Conocimiento", sura: "Al-Imran", suraNum: 3, ayah: 190, arabic: "إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِّأُولِي الْأَلْبَابِ", translation: "En la creación de los cielos y de la tierra y en la alternancia de la noche y el día hay ciertamente signos para los dotados de intelecto." },
    { category: "Dificultades", sura: "Inshirah", suraNum: 94, ayah: 5, arabic: "فَإِنَّ مَعَ الْعُسْرِ يُسْرًا", translation: "Ciertamente, con la dificultad viene la facilidad." },
    { category: "Dificultades", sura: "Al-Baqarah", suraNum: 2, ayah: 155, arabic: "وَلَنَبْلُوَنَّكُم بِشَيْءٍ مِّنَ الْخَوْفِ وَالْجُوعِ وَنَقْصٍ مِّنَ الْأَمْوَالِ وَالْأَنفُسِ وَالثَّمَرَاتِ ۗ وَبَشِّرِ الصَّابِرِينَ", translation: "Ciertamente os pondremos a prueba con algo de temor, hambre, pérdida de bienes, vidas y frutos. ¡Anuncia buenas nuevas a los pacientes!" },
    { category: "Dificultades", sura: "Al-Baqarah", suraNum: 2, ayah: 216, arabic: "وَعَسَىٰ أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ", translation: "Puede que detestéis algo cuando es un bien para vosotros." },
    { category: "Esperanza", sura: "Yusuf", suraNum: 12, ayah: 87, arabic: "وَلَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ ۖ إِنَّهُ لَا يَيْأَسُ مِن رَّوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ", translation: "No desesperéis de la misericordia de Allah. Solo desesperan de ella los incrédulos." },
    { category: "Esperanza", sura: "Inshirah", suraNum: 94, ayah: 6, arabic: "إِنَّ مَعَ الْعُسْرِ يُسْرًا", translation: "Sí, ciertamente con la dificultad viene la facilidad." },
    { category: "Esperanza", sura: "Ad-Duha", suraNum: 93, ayah: 5, arabic: "وَلَسَوْفَ يُعْطِيكَ رَبُّكَ فَتَرْضَىٰ", translation: "Y pronto tu Señor te dará y quedarás satisfecho." },
    { category: "Arrepentimiento", sura: "Al-Baqarah", suraNum: 2, ayah: 222, arabic: "إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ", translation: "Allah ama a quienes se arrepienten y aman a quienes se purifican." },
    { category: "Arrepentimiento", sura: "At-Tahrim", suraNum: 66, ayah: 8, arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا تُوبُوا إِلَى اللَّهِ تَوْبَةً نَّصُوحًا", translation: "¡Creyentes! Volved a Allah con un arrepentimiento sincero." },
    { category: "Arrepentimiento", sura: "Hud", suraNum: 11, ayah: 90, arabic: "وَاسْتَغْفِرُوا رَبَّكُمْ ثُمَّ تُوبُوا إِلَيْهِ", translation: "Pedid perdón a vuestro Señor y volveos a Él." },
    { category: "Paraíso", sura: "Al-Kahf", suraNum: 18, ayah: 107, arabic: "إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ كَانَتْ لَهُمْ جَنَّاتُ الْفِرْدَوْسِ نُزُلًا", translation: "Aquellos que creen y obran bien tendrán como alojamiento los Jardines del Paraíso (Al-Firdaws)." },
    { category: "Paraíso", sura: "As-Sajdah", suraNum: 32, ayah: 17, arabic: "فَلَا تَعْلَمُ نَفْسٌ مَّا أُخْفِيَ لَهُم مِّن قُرَّةِ أَعْيُنٍ", translation: "Nadie sabe cuánta alegría se les ha ocultado en compensación por sus obras." },
    { category: "Paraíso", sura: "Ar-Rahman", suraNum: 55, ayah: 46, arabic: "وَلِمَنْ خَافَ مَقَامَ رَبِّهِ جَنَّتَانِ", translation: "Habrá dos jardines para quien haya temido la comparecencia ante su Señor." },
    { category: "Temor de Allah", sura: "Al-Hashr", suraNum: 59, ayah: 59, arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللَّهَ", translation: "¡Creyentes! Temed a Allah." },
    { category: "Temor de Allah", sura: "At-Talaq", suraNum: 65, ayah: 2, arabic: "وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا", translation: "A quien tema a Allah, Él le dará una salida." },
    { category: "Temor de Allah", sura: "Al-Imran", suraNum: 3, ayah: 102, arabic: "يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللَّهَ حَقَّ تُقَاتِهِ", translation: "¡Creyentes! Temed a Allah como es debido." },
    { category: "Fe", sura: "Al-Baqarah", suraNum: 2, ayah: 285, arabic: "آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ", translation: "El Mensajero cree en lo que se le ha revelado de su Señor, y los creyentes también." },
    { category: "Fe", sura: "Al-Hijr", suraNum: 15, ayah: 99, arabic: "وَاعْبُدْ رَبَّكَ حَتَّىٰ يَأْتِيَكَ الْيَقِينُ", translation: "Adora a tu Señor hasta que te llegue la certeza." },
    { category: "Fe", sura: "Mu'minun", suraNum: 23, ayah: 2, arabic: "الَّذِينَ هُمْ فِي صَلَاتِهِمْ خَاشِعُونَ", translation: "Aquellos que son humildes en su oración." }
  ],
  surahs: [
    { num: 1, name: "Al-Fatihah", es: "La Apertura", arabic: "الفاتحة", verses: 7, type: "en" },
    { num: 2, name: "Al-Baqarah", es: "La Vaca", arabic: "البقرة", verses: 286, type: "en" },
    { num: 3, name: "Al-'Imran", es: "La Familia de 'Imran", arabic: "آل عمران", verses: 200, type: "en" },
    { num: 4, name: "An-Nisa'", es: "Las Mujeres", arabic: "النساء", verses: 176, type: "en" },
    { num: 5, name: "Al-Ma'idah", es: "La Mesa Servida", arabic: "المائدة", verses: 120, type: "en" },
    { num: 6, name: "Al-An'am", es: "Los Rebaños", arabic: "الأنعام", verses: 165, type: "en" },
    { num: 7, name: "Al-A'raf", es: "Los Límites", arabic: "الأعراف", verses: 206, type: "en" },
    { num: 8, name: "Al-Anfal", es: "Los Botines", arabic: "الأنفال", verses: 75, type: "en" },
    { num: 9, name: "At-Tawbah", es: "El Arrepentimiento", arabic: "التوبة", verses: 129, type: "en" },
    { num: 10, name: "Yunus", es: "Jonás", arabic: "يونس", verses: 109, type: "en" },
    { num: 11, name: "Hud", es: "Hud", arabic: "هود", verses: 123, type: "en" },
    { num: 12, name: "Yusuf", es: "José", arabic: "يوسف", verses: 111, type: "en" },
    { num: 13, name: "Ar-Ra'd", es: "El Trueno", arabic: "الرعد", verses: 43, type: "en" },
    { num: 14, name: "Ibrahim", es: "Abraham", arabic: "إبراهيم", verses: 52, type: "en" },
    { num: 15, name: "Al-Hijr", es: "La Roca", arabic: "الحجر", verses: 99, type: "en" },
    { num: 16, name: "An-Nahl", es: "Las Abejas", arabic: "النحل", verses: 128, type: "en" },
    { num: 17, name: "Al-Isra'", es: "El Viaje Nocturno", arabic: "الإسراء", verses: 111, type: "en" },
    { num: 18, name: "Al-Kahf", es: "La Caverna", arabic: "الكهف", verses: 110, type: "en" },
    { num: 19, name: "Maryam", es: "María", arabic: "مريم", verses: 98, type: "en" },
    { num: 20, name: "Taha", es: "Ta, Ha", arabic: "طه", verses: 135, type: "en" },
    { num: 21, name: "Al-Anbiya'", es: "Los Profetas", arabic: "الأنبياء", verses: 112, type: "en" },
    { num: 22, name: "Al-Hajj", es: "La Peregrinación", arabic: "الحج", verses: 78, type: "en" },
    { num: 23, name: "Al-Mu'minun", es: "Los Creyentes", arabic: "المؤمنون", verses: 118, type: "en" },
    { num: 24, name: "An-Nur", es: "La Luz", arabic: "النور", verses: 64, type: "en" },
    { num: 25, name: "Al-Furqan", es: "El Discernimiento", arabic: "الفرقان", verses: 77, type: "en" },
    { num: 26, name: "Ash-Shu'ara'", es: "Los Poetas", arabic: "الشعراء", verses: 227, type: "en" },
    { num: 27, name: "An-Naml", es: "Las Hormigas", arabic: "النمل", verses: 93, type: "en" },
    { num: 28, name: "Al-Qasas", es: "La Historia", arabic: "القصص", verses: 88, type: "en" },
    { num: 29, name: "Al-'Ankabut", es: "La Araña", arabic: "العنكبوت", verses: 69, type: "en" },
    { num: 30, name: "Ar-Rum", es: "Los Romanos", arabic: "الروم", verses: 60, type: "en" },
    { num: 31, name: "Luqman", es: "Luqman", arabic: "لقمان", verses: 34, type: "en" },
    { num: 32, name: "As-Sajdah", es: "La Prosternación", arabic: "السجدة", verses: 30, type: "en" },
    { num: 33, name: "Al-Ahzab", es: "Las Facciones", arabic: "الأحزاب", verses: 73, type: "en" },
    { num: 34, name: "Saba'", es: "Saba", arabic: "سبأ", verses: 54, type: "en" },
    { num: 35, name: "Fatir", es: "El Originador", arabic: "فاطر", verses: 45, type: "en" },
    { num: 36, name: "Ya-Sin", es: "Ya, Sin", arabic: "يس", verses: 83, type: "en" },
    { num: 37, name: "As-Saffat", es: "Los Ordenados en Filas", arabic: "الصافات", verses: 182, type: "en" },
    { num: 38, name: "Sad", es: "Sad", arabic: "ص", verses: 88, type: "en" },
    { num: 39, name: "Az-Zumar", es: "Los Grupos", arabic: "الزمر", verses: 75, type: "en" },
    { num: 40, name: "Ghafir", es: "El Perdonador", arabic: "غافر", verses: 85, type: "en" },
    { num: 41, name: "Fussilat", es: "Las Aleyas Detalladas", arabic: "فصلت", verses: 54, type: "en" },
    { num: 42, name: "Ash-Shura", es: "La Consulta", arabic: "الشورى", verses: 53, type: "en" },
    { num: 43, name: "Az-Zukhruf", es: "Los Ornamentos de Oro", arabic: "الزخرف", verses: 89, type: "en" },
    { num: 44, name: "Ad-Dukhan", es: "El Humo", arabic: "الدخان", verses: 59, type: "en" },
    { num: 45, name: "Al-Jathiyah", es: "La Arrodillada", arabic: "الجاثية", verses: 37, type: "en" },
    { num: 46, name: "Al-Ahqaf", es: "Las Dunas", arabic: "الأحقاف", verses: 35, type: "en" },
    { num: 47, name: "Muhammad", es: "Muhammad", arabic: "محمد", verses: 38, type: "en" },
    { num: 48, name: "Al-Fath", es: "La Victoria", arabic: "الفتح", verses: 29, type: "en" },
    { num: 49, name: "Al-Hujurat", es: "Los Aposentos Privados", arabic: "الحجرات", verses: 18, type: "en" },
    { num: 50, name: "Qaf", es: "Qaf", arabic: "ق", verses: 45, type: "en" },
    { num: 51, name: "Adh-Dhariyat", es: "Los Vientos", arabic: "الذاريات", verses: 60, type: "en" },
    { num: 52, name: "At-Tur", es: "El Monte", arabic: "الطور", verses: 49, type: "en" },
    { num: 53, name: "An-Najm", es: "La Estrella", arabic: "النجم", verses: 62, type: "en" },
    { num: 54, name: "Al-Qamar", es: "La Luna", arabic: "القمر", verses: 55, type: "en" },
    { num: 55, name: "Ar-Rahman", es: "El Misericordioso", arabic: "الرحمن", verses: 78, type: "en" },
    { num: 56, name: "Al-Waqi'ah", es: "El Evento", arabic: "الواقعة", verses: 96, type: "en" },
    { num: 57, name: "Al-Hadid", es: "El Hierro", arabic: "الحديد", verses: 29, type: "en" },
    { num: 58, name: "Al-Mujadilah", es: "La Discutidora", arabic: "المجادلة", verses: 22, type: "en" },
    { num: 59, name: "Al-Hashr", es: "La Reunión", arabic: "الحشر", verses: 24, type: "en" },
    { num: 60, name: "Al-Mumtahanah", es: "La Evaluada", arabic: "الممتحنة", verses: 13, type: "en" },
    { num: 61, name: "As-Saff", es: "La Fila", arabic: "الصف", verses: 14, type: "en" },
    { num: 62, name: "Al-Jumu'ah", es: "El Viernes", arabic: "الجمعة", verses: 11, type: "en" },
    { num: 63, name: "Al-Munafiqun", es: "Los Hipócritas", arabic: "المنافقون", verses: 11, type: "en" },
    { num: 64, name: "At-Taghabun", es: "La Mutua Negligencia", arabic: "التغابن", verses: 18, type: "en" },
    { num: 65, name: "At-Talaq", es: "El Divorcio", arabic: "الطلاق", verses: 12, type: "en" },
    { num: 66, name: "At-Tahrim", es: "La Prohibición", arabic: "التحريم", verses: 12, type: "en" },
    { num: 67, name: "Al-Mulk", es: "La Soberanía", arabic: "الملك", verses: 30, type: "en" },
    { num: 68, name: "Al-Qalam", es: "El Cálamo", arabic: "القلم", verses: 52, type: "en" },
    { num: 69, name: "Al-Haqqah", es: "La Realidad", arabic: "الحاقة", verses: 52, type: "en" },
    { num: 70, name: "Al-Ma'arij", es: "Las Vías de Ascenso", arabic: "المعارج", verses: 44, type: "en" },
    { num: 71, name: "Nuh", es: "Noé", arabic: "نوح", verses: 28, type: "en" },
    { num: 72, name: "Al-Jinn", es: "Los Yinnes", arabic: "الجن", verses: 28, type: "en" },
    { num: 73, name: "Al-Muzzammil", es: "El Envuelto", arabic: "المزمل", verses: 20, type: "en" },
    { num: 74, name: "Al-Muddaththir", es: "El Arropado", arabic: "المدثر", verses: 56, type: "en" },
    { num: 75, name: "Al-Qiyamah", es: "La Resurrección", arabic: "القيامة", verses: 40, type: "en" },
    { num: 76, name: "Al-Insan", es: "El Hombre", arabic: "الإنسان", verses: 31, type: "en" },
    { num: 77, name: "Al-Mursalat", es: "Las Enviadas", arabic: "المرسلات", verses: 50, type: "en" },
    { num: 78, name: "An-Naba'", es: "La Noticia", arabic: "النبأ", verses: 40, type: "en" },
    { num: 79, name: "An-Nazi'at", es: "Los Arrancadores", arabic: "النازعات", verses: 46, type: "en" },
    { num: 80, name: "'Abasa", es: "Frunció el Ceño", arabic: "عبس", verses: 42, type: "en" },
    { num: 81, name: "At-Takwir", es: "El Oscurecimiento", arabic: "التكوير", verses: 29, type: "en" },
    { num: 82, name: "Al-Infitar", es: "La Fractura", arabic: "الانفطار", verses: 19, type: "en" },
    { num: 83, name: "Al-Mutaffifin", es: "Los Defraudadores", arabic: "المطففين", verses: 36, type: "en" },
    { num: 84, name: "Al-Inshiqaq", es: "La Hendidura", arabic: "الانشقاق", verses: 25, type: "en" },
    { num: 85, name: "Al-Buruj", es: "Las Constelaciones", arabic: "البروج", verses: 22, type: "en" },
    { num: 86, name: "At-Tariq", es: "La Estrella Nocturna", arabic: "الطارق", verses: 17, type: "en" },
    { num: 87, name: "Al-A'la", es: "El Altísimo", arabic: "الأعلى", verses: 19, type: "en" },
    { num: 88, name: "Al-Ghashiyah", es: "El Día Abrumador", arabic: "الغاشية", verses: 26, type: "en" },
    { num: 89, name: "Al-Fajr", es: "El Amanecer", arabic: "الفجر", verses: 30, type: "en" },
    { num: 90, name: "Al-Balad", es: "La Ciudad", arabic: "البلد", verses: 20, type: "en" },
    { num: 91, name: "Ash-Shams", es: "El Sol", arabic: "الشمس", verses: 15, type: "en" },
    { num: 92, name: "Al-Layl", es: "La Noche", arabic: "الليل", verses: 21, type: "en" },
    { num: 93, name: "Ad-Duha", es: "La Luz Matinal", arabic: "الضحى", verses: 11, type: "en" },
    { num: 94, name: "Al-Inshirah", es: "La Serena Expansión", arabic: "الشرح", verses: 8, type: "en" },
    { num: 95, name: "At-Tin", es: "El Higal", arabic: "التين", verses: 8, type: "en" },
    { num: 96, name: "Al-'Alaq", es: "El Coágulo", arabic: "العلق", verses: 19, type: "en" },
    { num: 97, name: "Al-Qadr", es: "El Decreto / La Noche del Destino", arabic: "القدر", verses: 5, type: "en" },
    { num: 98, name: "Al-Bayyinah", es: "La Evidencia Clara", arabic: "البينة", verses: 8, type: "en" },
    { num: 99, name: "Az-Zalzalah", es: "El Terremoto", arabic: "الزلزلة", verses: 8, type: "en" },
    { num: 100, name: "Al-'Adiyat", es: "Las Corredoras", arabic: "العاديات", verses: 11, type: "en" },
    { num: 101, name: "Al-Qari'ah", es: "El Golpe Abrumador", arabic: "القارعة", verses: 11, type: "en" },
    { num: 102, name: "At-Takathur", es: "La Afán de Acumular", arabic: "التكاثر", verses: 8, type: "en" },
    { num: 103, name: "Al-'Asr", es: "El Tiempo", arabic: "العصر", verses: 3, type: "en" },
    { num: 104, name: "Al-Humazah", es: "El Murmurador", arabic: "الهمزة", verses: 9, type: "en" },
    { num: 105, name: "Al-Fil", es: "El Elefante", arabic: "الفيل", verses: 5, type: "en" },
    { num: 106, name: "Quraysh", es: "Quraysh", arabic: "قريش", verses: 4, type: "en" },
    { num: 107, name: "Al-Ma'un", es: "La Ayuda", arabic: "الماعون", verses: 7, type: "en" },
    { num: 108, name: "Al-Kawthar", es: "La Abundancia", arabic: "الكوثر", verses: 3, type: "en" },
    { num: 109, name: "Al-Kafirun", es: "Los Incrédulos", arabic: "الكافرون", verses: 6, type: "en" },
    { num: 110, name: "An-Nasr", es: "La Victoria", arabic: "النصر", verses: 3, type: "en" },
    { num: 111, name: "Al-Masad", es: "La Fibra de Palmera", arabic: "المسد", verses: 5, type: "en" },
    { num: 112, name: "Al-Ikhlas", es: "La Pureza de la Fe", arabic: "الإخلاص", verses: 4, type: "en" },
    { num: 113, name: "Al-Falaq", es: "El Alba", arabic: "الفلق", verses: 5, type: "en" },
    { num: 114, name: "An-Nas", es: "La Humanidad", arabic: "الناس", verses: 6, type: "en" }
  ]
};