/* ================================================
   DATA: Ciencia y civilización islámica
   ================================================ */
window.SCIENCE_DATA = [
  { area: "Matemáticas", period: "Siglo VIII-XIII", figure: "Al-Jwarizmi", figureAr: "الخوارزمي", desc: "Fundador del álgebra y difusor del sistema de numeración indo-arábiga (cifras 0-9). La palabra 'algoritmo' proviene de su nombre.", refs: "Su obra principal: Al-Jabr wal-Muqabala (ca. 820). No se le atribuye la invención del cero, sino la introducción del sistema en Occidente." },
  { area: "Matemáticas", period: "Siglo IX-X", figure: "Al-Uqlidisi", figureAr: "الأقيليدسي", desc: "Fue el primero en usar cifras indo-arábigas de forma práctica en su libro 'El arte de los cálculos' (874).", refs: "Sin atribuciones dudosas." },
  { area: "Matemáticas", period: "Siglo X", figure: "Abu al-Wafa' al-Buzjani", figureAr: "أبو الوفاء البوزجاني", desc: "Introductor de funciones trigonométricas como el tangente y el secante; autor de tratados avanzados de geometría.", refs: "Su obra es reconocida por historiadores de las matemáticas." },
  { area: "Medicina", period: "Siglo IX-X", figure: "Ibn Sina (Avicena)", figureAr: "ابن سينا", desc: "Su Canon de Medicina fue texto de referencia en Europa y el mundo islámico durante siglos. Clasificó y sistematizó enfermedades, diagnósticos y tratamientos.", refs: "Canon de Medicina (al-Qanun fi al-Tibb), ca. 1025. Obra extensa y rigurosa para su época." },
  { area: "Medicina", period: "Siglo X-XI", figure: "Al-Razi (Rhazes)", figureAr: "الرازي", desc: "Médico persa que distinguió por primera vez la viruela del sarampión; autor del Kitab al-Hawi, enciclopedia médica monumental.", refs: "Kitab al-Hawi, al-Mansuri y otros trabajos médicos reconocidos." },
  { area: "Medicina", period: "Siglo XIII", figure: "Ibn al-Nafis", figureAr: "ابن النفيس", desc: "Describió la circulación pulmonar antes que Harvey. Fue el primero en explicar correctamente cómo la sangre viaja del corazón al pulmón y de vuelta.", refs: "Comentario sobre la anatomía de Ibn Sina. No ha sido sobrevalorado." },
  { area: "Astronomía", period: "Siglo IX-X", figure: "Al-Battani", figureAr: "البتاني", desc: "Astrónomo y matemático que refinó los cálculos del año solar, la órbita y la posición de las estrellas con precisión sin precedentes para su época.", refs: "Su obra al-Zij al-Sabi'i fue traducida al latín y usada por Copérnico." },
  { area: "Astronomía", period: "Siglo IX-X", figure: "Al-Sufi", figureAr: "الصوفي", desc: "Su 'Libro de las Estrellas Fijas' incluye observaciones originales y es la fuente de la primera observación registrada de la galaxia de Andrómeda.", refs: "El suyo es uno de los primeros registros escritos de Andrómeda." },
  { area: "Óptica", period: "Siglo XI", figure: "Ibn al-Haytham", figureAr: "ابن الهيثم", desc: "Padre de la óptica moderna. Su Kitab al-Manazir (Libro de Óptica) explicó la visión y la refracción de la luz con métodos experimentales.", refs: "Kitab al-Manazir (ca. 1021), reconocido como obra pionera del método científico." },
  { area: "Arquitectura", period: "Siglo VIII-XV", figure: "Diversas civilizaciones", figureAr: "متعدد", desc: "La arquitectura islámica desarrolló la cúpula, los arcos, el muqarnas, las jardines y los sistemas hidráulicos. Ejemplos: la Mezquita de Córdoba, la Alhambra y las escuelas de Bagdad.", refs: "Obras arquitectónicas documentadas y vigentes." },
  { area: "Filosofía", period: "Siglo IX-X", figure: "Al-Kindi", figureAr: "الكندي", desc: "Conocido como 'el filósofo de los árabes', integró la filosofía griega con el pensamiento islámico.", refs: "Su obra filosófica es reconocida académicamente." },
  { area: "Filosofía", period: "Siglo XI", figure: "Ibn Rushd (Averroes)", figureAr: "ابن رشد", desc: "Su comentario sobre Aristóteles influyó profundamente en la filosofía europea medieval. Defendió la compatibilidad entre razón y fe.", refs: "Tahafut al-Tahafut (La refutación de la refutación) y comentarios aristotélicos." },
  { area: "Ingeniería", period: "Siglo XIII", figure: "Al-Jazari", figureAr: "الجزري", desc: "Ingeniero que diseñó dispositivos mecánicos complejos, antepasados de los engranajes y el eje de manivela. Su Libro del Conocimiento de los Ingeniosos Mecanismos es una obra precursora de la robótica.", refs: "Kitab fi Ma'rifat al-Hiyal al-Handasiyya (1206), obra documentada." },
  { area: "Agricultura", period: "Siglo X-XIII", figure: "Civilización hispano-árabe", figureAr: "الأندلس", desc: "En al-Ándalus se desarrollaron sistemas de riego avanzados, la agricultura intensiva y la introducción de nuevas variedades (naranja, azúcar, algodón).", refs: "Documentación histórica sobre la agricultura andalusí." },
  { area: "Navegación", period: "Siglo X-XIII", figure: "Científicos árabes", figureAr: "العلماء العرب", desc: "Desarrollaron instrumentos como el astrolabio y la qibla compass, mejorando la navegación y la determinación de la dirección de la oración.", refs: "Instrumentos conservados en museos y descritos en tratados." },
  { area: "Agricultura", period: "Siglo XV", figure: "Ibn al-Baytar", figureAr: "ابن البيطار", desc: "Botánico y farmacólogo que catalogó más de 1400 plantas y sustancias medicinales, su obra fue referencia en Europa hasta el siglo XVIII.", refs: "Kitab al-Jami' li-Mufradat al-Adwiya wa al-Aghdhiya, ca. 1240." }
];

window.SCIENCE_META = {
  note: "No se exagera ni atribuyen descubrimientos sin base. Las contribuciones se basan en evidencia histórica sólida. Las fechas son aproximadas y la información pertenece al conocimiento académico establecido."
};